### ISSUE TITLE
installation error

### ISSUE THREAD

**Issue by yenla9** [vincent-vdb/japanese-candlestick-pattern#16]
![image](https://user-images.githubusercontent.com/113557713/213610193-99b9a474-a69d-4d0d-ad52-aa6c4fb5626d.png)

**Comment by vincent-vdb** [comment]
Hi, can you please provide more context about your environment? E.g.: python version, pip version
Also, can you provide the full stack trace of the error? There are probably more errors above this message that may be useful.

**Comment by vincent-vdb** [comment]
After offline discussion, it turns out it was an environment issue and not related to the library itself.
